# Generated by Django 2.2.13 on 2020-06-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsyat',
            name='name',
        ),
        migrations.AlterField(
            model_name='formsyat',
            name='From',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='formsyat',
            name='To',
            field=models.CharField(max_length=10),
        ),
    ]
